### ISSUE TITLE
Bot doesn't go to limbo

### ISSUE THREAD

**Issue by RagingEnby** [aidn3/hypixel-guild-discord-bridge#38] opened 2023-03-03 04:10 UTC
I belive hypixel has patched using the squiggly color code symbol to go to limbo. Any way to still do something like this?

**Comment by aidn3** [comment] 2023-03-05 15:55
I can't think of any safe method to achieve that. 

Possible solutions:
- We can try to crash the connection by sending invalid packets, But then Hypixel has been warning to never mess with packets.
- We can also try to put the socket on hold and spoof "poor connection" which can also send you to limbo, but that method can be detected as well. It is the best bet.

**Comment by aidn3** [comment] 2023-08-05 08:35
Seems like Hypixel patched the bug then rolled back.

```logs
[2023-08-05T10:10:52.963] [DEBUG] Guild - Spawn event triggered. sending to limbo...
[2023-08-05T10:10:53.101] [INFO] Main - [minecraftChat] [{"localEvent":true,"instanceName":"Guild","location":"minecraft","message":"A kick occurred in your connection, so you have been routed to limbo!"}]
[2023-08-05T10:10:53.102] [INFO] Main - [minecraftChat] [{"localEvent":true,"instanceName":"Guild","location":"minecraft","message":"Illegal characters in chat"}]
```

I'll close the issue since the problem is gone.

**Closed by aidn3** 2023-08-05 08:35 UTC
Labels: bug
